
import pyautogui
import time


#To use this script, Have chrome tag open with Youtube's tag textbox selected, alt tab to this script and press F5 (or however you execute the file)


pyautogui.hotkey('alt','tab')

#Commands - do NOT alt tab back to text chats during execution
pyautogui.write("Chatrat's Revenge")
pyautogui.press('enter')
pyautogui.write("Chatrats Revenge")
pyautogui.press('enter')
pyautogui.write("Lucy Pyre")
pyautogui.press('enter')
pyautogui.write("LucyPyre")
pyautogui.press('enter')
pyautogui.write("fangame")
pyautogui.press('enter')
pyautogui.write("Fan Game")
pyautogui.press('enter')
pyautogui.write("fan-game")
pyautogui.press('enter')
pyautogui.write("VTuber")
pyautogui.press('enter')
pyautogui.write("VTuber game")
pyautogui.press('enter')
pyautogui.write("anime")
pyautogui.press('enter')
pyautogui.write("turnbased")
pyautogui.press('enter')
pyautogui.write("turn-based")
pyautogui.press('enter')
pyautogui.write("turn based")
pyautogui.press('enter')
pyautogui.write("ratJAM")
pyautogui.press('enter')
pyautogui.write("ratJAM game")
pyautogui.press('enter')
pyautogui.write("twitch")
pyautogui.press('enter')
pyautogui.write("twitch game")
pyautogui.press('enter')
pyautogui.write("Cringe game")
pyautogui.press('enter')
pyautogui.write("python game")
pyautogui.press('enter')
pyautogui.write("pygame game")
pyautogui.press('enter')
pyautogui.write("rat game")
pyautogui.press('enter')
pyautogui.write("chatrat")
pyautogui.press('enter')
pyautogui.write("chat rat")
pyautogui.press('enter')
pyautogui.write("chatrat game")
pyautogui.press('enter')
pyautogui.write("chat rat game")
pyautogui.press('enter')
pyautogui.write("V-Tuber")
pyautogui.press('enter')
pyautogui.write("V-Tuber game")
pyautogui.press('enter')
pyautogui.write("V tuber")
pyautogui.press('enter')
pyautogui.write("V tuber game")
pyautogui.press('enter')


